StreetWorkout/Models/Home/IndexViewModel.cs
namespace StreetWorkout.Models.Home
{
    using System.Collections.Generic;

    public class IndexViewModel
    {
        public bool IsTrainer { get; set; }

        public bool IsAccountCompleted { get; set; }

        public List<UserIndexViewModel> Users { get; set; }
    }
}

StreetWorkout/Models/Home/UserIndexViewModel.cs
namespace StreetWorkout.Models.Home
{
    public class UserIndexViewModel
    {
        public string Username { get; set; }

        public string ImageUrl { get; set; }
    }
}

StreetWorkout/Areas/Administration/Controllers/HomeController.cs
namespace StreetWorkout.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using static WebConstants;

    [Authorize(Roles = AdministratorRoleName)]
    public class HomeController : AdministrationController
    {
        public IActionResult Index()
            => this.View();
    }
}

StreetWorkout/Controllers/AccountsController.cs
namespace StreetWorkout.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using StreetWorkout.Infrastructure;
    using StreetWorkout.Services.Accounts;
    using StreetWorkout.ViewModels.Accounts;

    using static WebConstants;
    using static WebConstants.ModelStateMessage;

    [Authorize]
    public class AccountsController : Controller
    {
        private const string RedirectIndexActionName = nameof(HomeController.Index);
        private const string RedirectAccountActionName = nameof(Account);
        private const string RedirectControllerName = "Home";

        private readonly IAccountService accountService;

        public AccountsController(IAccountService accountService)
            => this.accountService = accountService;

        public async Task<IActionResult> Account(string username)
            => this.View(await this.accountService.GetAccount(username));

        public async Task<IActionResult> CompleteAccount()
            => await this.IsAccountComplete()
                ? this.RedirectToAction(RedirectIndexActionName, RedirectControllerName)
                : this.View(new AccountFormModel
                {
                    Sports = await this.accountService.GetSportsInAccountFormModel(),
                    Goals = await this.accountService.GetGoalsInAccountFormModel(),
                    TrainingFrequencies = await this.accountService.GetTrainingFrequenciesInAccountFormModel(),
                });

        [HttpPost]
        public async Task<IActionResult> CompleteAccount(AccountFormModel data)
        {
            var userId = this.User.GetId();

            if (await this.IsAccountComplete() || await this.accountService.IsUserDataExists(userId))
            {
                return this.RedirectToAction(RedirectIndexActionName, RedirectControllerName);
            }

            if (!await this.accountService.IsValidSportId(data.SportId))
            {
                this.ModelState.AddModelError(nameof(data.SportId), InvalidSport);
            }

            if (!await this.accountService.IsValidGoalId(data.GoalId))
            {
                this.ModelState.AddModelError(nameof(data.GoalId), InvalidGoal);
            }

            if (!await this.accountService.IsValidTrainingFrequencyId(data.TrainingFrequencyId))
            {
                this.ModelState.AddModelError(nameof(data.TrainingFrequencyId), InvalidTrainingFrequency);
            }

            if (!this.ModelState.IsValid)
            {
                data.Sports = await this.accountService.GetSportsInAccountFormModel();
                data.Goals = await this.accountService.GetGoalsInAccountFormModel();
                data.TrainingFrequencies = await this.accountService.GetTrainingFrequenciesInAccountFormModel();

                return this.View(data);
            }

            await this.accountService.CompleteAccount(userId, data.SportId, data.GoalId, data.TrainingFrequencyId, data.Weight, data.Height, data.Description);

            return this.RedirectToAction(RedirectIndexActionName, RedirectControllerName);
        }

        public async Task<IActionResult> Edit(string userId)
        {
            if (!await this.accountService.IsUserAccountComplete(userId))
            {
                return this.BadRequest(CannotEditAccount);
            }

            if (this.User.GetId() != userId && !this.User.IsInRole(AdministratorRoleName))
            {
                return this.Unauthorized();
            }

            var model = await this.accountService.GetEditFormModel(userId);
            model.Sports = await this.accountService.GetSportsInAccountFormModel();
            model.Goals = await this.accountService.GetGoalsInAccountFormModel();
            model.TrainingFrequencies = await this.accountService.GetTrainingFrequenciesInAccountFormModel();

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditFormModel model)
        {
            if (!await this.accountService.IsUserAccountComplete(model.Id))
            {
                return this.BadRequest(CannotEditAccount);
            }

            if (this.User.GetId() != model.Id && !this.User.IsInRole(AdministratorRoleName))
            {
                return this.Unauthorized();
            }

            if (!await this.accountService.IsValidSportId(model.SportId))
            {
                this.ModelState.AddModelError(nameof(model.SportId), InvalidSport);
            }

            if (!await this.accountService.IsValidGoalId(model.GoalId))
            {
                this.ModelState.AddModelError(nameof(model.GoalId), InvalidGoal);
            }

            if (!await this.accountService.IsValidTrainingFrequencyId(model.TrainingFrequencyId))
            {
                this.ModelState.AddModelError(nameof(model.TrainingFrequencyId), InvalidTrainingFrequency);
            }

            if (!this.ModelState.IsValid)
            {
                model.Sports = await this.accountService.GetSportsInAccountFormModel();
                model.Goals = await this.accountService.GetGoalsInAccountFormModel();
                model.TrainingFrequencies = await this.accountService.GetTrainingFrequenciesInAccountFormModel();
                return this.View(model);
            }

            if (!await this.accountService.Edit(model.Id, model.ImageUrl, model.Weight, model.Height, model.City, model.Description, model.SportId, model.GoalId, model.TrainingFrequencyId))
            {
                return this.BadRequest();
            }

            return this.RedirectToAction(RedirectAccountActionName, new { username = model.Username });
        }

        public async Task<IActionResult> EditImage(string userId)
        {
            if (!this.User.IsInRole(AdministratorRoleName))
            {
                return this.Unauthorized();
            }

            return this.View(await this.accountService.GetEditImageFormModel(userId));
        }

        [HttpPost]
        public async Task<IActionResult> EditImage(EditImageFormModel model)
        {
            if (!this.User.IsInRole(AdministratorRoleName))
            {
                return this.Unauthorized();
            }

            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            if (!await this.accountService.EditImage(model.Id, model.ImageUrl))
            {
                return this.BadRequest();
            }

            return this.RedirectToAction(RedirectAccountActionName, new { username = model.UserName });
        }

        private async Task<bool> IsAccountComplete()
            => await this.accountService.IsUserAccountComplete(this.User.GetId());
    }
}

StreetWorkout/Controllers/HomeController.cs
namespace StreetWorkout.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Memory;
    using StreetWorkout.Infrastructure;
    using StreetWorkout.Services.Homes;
    using StreetWorkout.Services.Homes.Models;
    using StreetWorkout.Services.Supplements.Models;
    using StreetWorkout.Services.Workouts.Models;
    using StreetWorkout.ViewModels;

    public class HomeController : Controller
    {
        private readonly IHomeService homeService;
        private readonly IMemoryCache cache;

        public HomeController(IHomeService homeService, IMemoryCache cache)
        {
            this.homeService = homeService;
            this.cache = cache;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            const string LatestWorkoutsCacheKey = "WorkoutsKey";
            const string UsersCacheKey = "UsersKey";
            const string SupplementsCacheKey = "SupplementsCacheKey";

            var latestWorkouts = this.cache.Get<IEnumerable<WorkoutServiceModel>>(LatestWorkoutsCacheKey);
            var users = this.cache.Get<IEnumerable<UserIndexServiceModel>>(UsersCacheKey);
            var latestSupplements = this.cache.Get<IEnumerable<SupplementServiceModel>>(SupplementsCacheKey);

            if (latestWorkouts == null || users == null || latestSupplements == null)
            {
                latestWorkouts = await this.homeService.Workouts();
                users = await this.homeService.Users();
                latestSupplements = await this.homeService.Supplements();

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(10));

                this.cache.Set(LatestWorkoutsCacheKey, latestWorkouts, cacheOptions);
                this.cache.Set(UsersCacheKey, users, cacheOptions);
                this.cache.Set(SupplementsCacheKey, latestSupplements, cacheOptions);
            }

            var model = await this.homeService.IndexViewModel(this.User.GetId());
            model.LatestWorkouts = latestWorkouts;
            model.Users = users;
            model.LatestSupplements = latestSupplements;

            return this.View(model);
        }

        public IActionResult Privacy()
            => this.View();

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
            => this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
    }
}

StreetWorkout/Controllers/SupplementsController.cs
namespace StreetWorkout.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using StreetWorkout.Infrastructure;
    using StreetWorkout.Services.Supplements;
    using StreetWorkout.Services.Supplements.Models;
    using StreetWorkout.ViewModels.Supplements;
    using static WebConstants.TempDataMessageKeys;

    [Authorize]
    public class SupplementsController : Controller
    {
        private readonly ISupplementService supplements;

        public SupplementsController(ISupplementService supplements)
            => this.supplements = supplements;

        public async Task<IActionResult> All([FromQuery] SupplementsQueryModel query)
        {
            var model = await this.supplements.All(query.CurrentPage, query.SearchTerms, query.CategoryId);

            if (model.TotalSupplements == 0)
            {
                this.TempData[NotFoundDataKey] = string.Format(NotFoundDataMessage, typeof(SupplementsController).GetControllerName());
            }

            return this.View(model);
        }

        public async Task<IActionResult> Details(int id)
            => this.View(await this.supplements.Details(id));

        public async Task<IActionResult> Buy(int id)
            => this.View(new BuySupplementFormModel
            {
                SupplementModel = await this.supplements.BuySupplementModel<BuySupplementViewModel>(id),
            });

        [HttpPost]
        public async Task<IActionResult> Buy(BuySupplementFormModel model)
        {
            if (!await this.supplements.IsValidSupplementId(model.SupplementId))
            {
                return this.BadRequest();
            }

            if (!this.ModelState.IsValid)
            {
                model.SupplementModel = await this.supplements.BuySupplementModel<BuySupplementViewModel>(model.SupplementId);
                return this.View(model);
            }

            await this.supplements.BuySupplement(model.SupplementId, this.User.GetId(), model.FirstName, model.LastName, model.PhoneNumber, model.Email, model.Address, model.CardName, model.CardNumber, model.Expiration);

            return this.RedirectToAction(nameof(ThankYou));
        }

        public IActionResult ThankYou()
            => this.View();
    }
}

StreetWorkout/Views/Home/Index.cshtml
@model IndexServiceModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <h1 class="display-4">Welcome <br> @(Model.IsTrainer ? "Trainer" : "Enthusiast").</h1>
                <p class="lead my-4">
                    @(Model.IsAccountCompleted ? "Your account is fully completed." : "Your account is not completed. Please complete your account to use all of the functionality of the website.")
                    <br> Enjoy yourself with us ...
                    <br /> And move your body to the next level because, the movements are healthy.
                </p>
            </div>
            <div class="col-12 col-md-6">
                <div class="devices pl-md-4 pt-5 pt-md-0">
                    <img src="https://static.sportzbusiness.com/uploads/2020/04/Athletes.jpg" alt="Example Navbar 1" class="img-fluid">
                </div>
            </div>
        </div>
    </div>
</div>
@if (!Model.IsAccountCompleted)
{
    <br />
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <i class="fa fa-exclamation-circle"></i>
        <strong>Hey!</strong> Your account is not completed
        <a asp-controller="Accounts" asp-action="CompleteAccount">click here.</a> to complete your account. This will unlock more options for you.
    </div>
}
<br />
<div class="features">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4">
                <div class="feature">
                    <div class="big-icon text-primary"><i class="fas fa-tools"></i></div>
                    <h5 class="text-primary">Learn From The Best</h5>
                    <p class="lead">Here you will find a wide range of experienced coaches and you will have the opportunity to learn from the best.</p>
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="feature">
                    <div class="big-icon text-secondary"><i class="fas fa-puzzle-piece"></i></div>
                    <h5 class="text-secondary">Workouts &amp; Diets</h5>
                    <p class="lead">The workouts and diets we offer are suitable for both beginners and advanced.</p>
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="feature">
                    <div class="big-icon text-success"><i class="fas fa-palette"></i></div>
                    <h5 class="text-success">Nutrition Plan</h5>
                    <p class="lead">Each user can receive an individual training and nutrition plan, specially prepared according to the needs and the desired goal to achieve the best possible results.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="blog-posts">
    <div class="text-center">
        <h2>Latest Supplements</h2>
        <br />
    </div>
    <div class="container">
        <div class="row">
            @foreach (var supplement in Model.LatestSupplements)
            {
                <div class="col-sm-6 col-md-4 mb-4">
                    <div class="component">
                        <div class="card card-home-height">
                            <div class="card-header">
                                <img class="card-img card-home-img" src="@supplement.ImageUrl" alt="@supplement.Name">
                            </div>
                            <div class="card-body">
                                <span class="badge badge-success mb-2">@supplement.Category</span>
                                <h4 class="card-title">@supplement.Name</h4>
                                <p class="card-text">Price: <b>@supplement.Price BGN</b></p>
                                <p class="card-text">Quantity: <b>@((supplement.Quantity / 1000.0).ToString("F3")) kg</b></p>
                            </div>
                            <div class="card-footer">
                                <a asp-controller="Supplements" asp-action="Details" asp-route-id="@supplement.Id" class="btn btn-primary">View More</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<br />
<div class="blog-posts">
    <div class="text-center">
        <h2>Latest Workouts</h2>
        <br />
    </div>
    <div class="container">
        <partial name="_WorkoutsPartial" model="Model.LatestWorkouts" />
    </div>
</div>
<br />
<div class="testimonials">
    <div class="info text-center">
        <h2>Opinions From Our Clients</h2>
        <br />
    </div>
    <div class="container text-center">
        <div class="row">
            <div class="col-12 col-md-3">
                <div class="testimonial d-flex flex-column align-items-center">
                    <div class="big-bubble bg-info bubble-top-left"></div>
                    <p class="lead font-italic">"I am extremely pleased with the results I have achieved, thanks to the entire team of the site. I recommend to all my friends!"</p>
                    <p>
                        <b>Cathee V.</b>,<br>
                        Fitness Enthusiast
                    </p>
                </div>
            </div>
            <div class="col-12 col-md-3">
                <div class="testimonial d-flex flex-column align-items-center mt-md-4">
                    <div class="big-bubble"></div>
                    <p class="lead font-italic">"Thanks to the training and the advice of the specialists, I achieved results I never dreamed of. Congratulations! Keep inspiring!"</p>
                    <p>
                        <b>Tom B.</b>,<br>
                        CrossFit Enthusiast
                    </p>
                </div>
            </div>
            <div class="col-12 col-md-3">
                <div class="testimonial d-flex flex-column align-items-center">
                    <div class="big-bubble bg-warning bubble-top-right"></div>
                    <p class="lead font-italic">"I am glad that I came across this site / forum, because here I met a lot of athletes, we exchanged tips, trained together and achieved a really big transformation !!"</p>
                    <p>
                        <b>Billie A.</b>,<br>
                        Athlete
                    </p>
                </div>
            </div>
            <div class="col-12 col-md-3">
                <div class="testimonial d-flex flex-column align-items-center mt-md-4">
                    <div class="big-bubble bg-success bubble-bottom-right"></div>
                    <p class="lead font-italic">"The best coaches gathered in one place !! Whichever one you choose as a mentor, you will not regret it !!"</p>
                    <p>
                        <b>Jack F.</b>,<br>
                        Kick-Boxer
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<h2 class="text-center">Latest Register Users</h2>
<br />
<div class="row">
    @foreach (var user in Model.Users)
    {
        <div class="col-md-4">
            <div class="component">
                <div class="card card-home-height">
                    <div class="card-header">
                        <img class="card-img card-home-img" src="@user.ImageUrl" alt="@user.UserName">
                    </div>
                    <div class="card-body">
                        <span class="badge badge-success mb-2">@user.UserRole</span>
                        <h4 class="card-title">@user.UserName</h4>
                        <p class="card-text">Country: <b>@user.Country</b></p>
                        <p class="card-text">Gender: <b>@user.Gender</b></p>
                        <p class="card-text">Age: <b>@user.Age Years</b></p>
                    </div>
                    <div class="card-footer">
                        <a asp-controller="Accounts" asp-action="Account" asp-route-username="@user.UserName" class="btn btn-primary">View More</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<br />

<div class="text-center">
    <button id="show-stats-btn" class="btn btn-info">Show Statistics</button>
</div>

<div id="show-stats" class="jumbotron d-none">
    <div class="row">
        <h2 id="total-trainers" class="col-md-4 text-center"></h2>
        <h2 id="total-enthusiasts" class="col-md-4 text-center"></h2>
        <h2 id="total-workouts" class="col-md-4 text-center"></h2>
    </div>
</div>

@section Scripts {
    <script src="~/js/index.js" asp-append-version="true"></script>
}